Repository atoptima/Coluna.jl, pull requests merged in 2020-02, with the labels that each got.

#250 Fix round in fill primal result
  src/MathProg/MOIinterface.jl
  test/full_instances_tests.jl
Labels: bug

#240 New organisation of algorithms
  src/Algorithm/Algorithm.jl
  src/Algorithm/benders.jl
  src/Algorithm/branching/abstractbranching.jl
  src/Algorithm/branching/branchingalgo.jl
  src/Algorithm/branching/branchinggroup.jl
  src/Algorithm/branching/branchingrule.jl
  src/Algorithm/branching/varbranching.jl
  src/Algorithm/colgen.jl
  src/Algorithm/conquer.jl
  src/Algorithm/divide.jl
  src/Algorithm/interface.jl
  src/Algorithm/masteripheur.jl
  src/Algorithm/masterlp.jl
  src/Algorithm/node.jl
  src/Algorithm/preprocessing.jl
  src/Algorithm/record.jl
  src/Algorithm/reformulationsolver.jl
  src/Algorithm/strategies/conquer/simplebenders.jl
  src/Algorithm/strategies/conquer/simplebnp.jl
  src/Algorithm/strategies/divide/simplebranching.jl
  src/Algorithm/strategies/explore/simplestrategies.jl
  src/Algorithm/strategies/strategy.jl
  src/Algorithm/treesearch.jl
  src/Coluna.jl
  src/MathProg/MOIinterface.jl
  src/MathProg/MathProg.jl
  src/MathProg/formulation.jl
  src/MathProg/incumbents.jl
  src/MathProg/optimizationresults.jl
  src/MathProg/reformulation.jl
  src/MathProg/types.jl
  src/optimize.jl
  src/parameters.jl
  test/full_instances_tests.jl
  test/preprocessing_tests.jl
  test/pricing_callback_tests.jl
  test/runtests.jl
  test/show_functions_tests.jl
  test/unit/algorithms/algorithm.jl
  test/unit/algorithms/masteripheur.jl
  test/unit/strategies/strategy.jl
  test/unit/unit_tests.jl
Labels: Algo

#258 Update Coluna parameters
  docs/src/start.md
Labels: documentation

#265 Print method for duties (nestedenum macro)
  src/Containers/nestedenum.jl
Labels: MathProg

#263 Fix check if column exists
  Manifest.toml
  src/Algorithm/colgen.jl
  src/Containers/Containers.jl
  src/Containers/solsandbounds.jl
  src/MathProg/formulation.jl
  src/MathProg/manager.jl
  src/MathProg/projection.jl
  src/parameters.jl
Labels: bug

#272 Dual sol pool matrix is dynamic sparse
  src/Algorithm/benders.jl
  src/Containers/Containers.jl
  src/Containers/members.jl
  src/MathProg/formulation.jl
  src/MathProg/manager.jl
  test/unit/containers/members.jl
  test/unit/unit_tests.jl
  test/unit/vcdict.jl
Labels: MathProg

#273 Introduce AbstractModel
  src/Containers/Containers.jl
  src/Containers/interface.jl
  src/MathProg/reformulation.jl
  src/MathProg/types.jl
Labels: design

#274 Abolish ElemDict
  src/Containers/Containers.jl
  src/Containers/elements.jl
  src/Containers/members.jl
  src/Containers/nestedenum.jl
  src/MathProg/decomposition.jl
  src/MathProg/formulation.jl
  src/MathProg/manager.jl
  src/MathProg/optimizerwrappers.jl
  test/pricing_callback_tests.jl
Labels: MathProg
