Repository atoptima/Coluna.jl, pull requests merged in 2020-05, with the labels that each got.

#323 Implementation of Storages and StorageStates
  src/Algorithm/Algorithm.jl
  src/Algorithm/benders.jl
  src/Algorithm/branching/branchingalgo.jl
  src/Algorithm/branching/branchinggroup.jl
  src/Algorithm/branching/branchingrule.jl
  src/Algorithm/branching/varbranching.jl
  src/Algorithm/colgen.jl
  src/Algorithm/conquer.jl
  src/Algorithm/data.jl
  src/Algorithm/divide.jl
  src/Algorithm/formstorages.jl
  src/Algorithm/interface.jl
  src/Algorithm/node.jl
  src/Algorithm/preprocessing.jl
  src/Algorithm/solveipform.jl
  src/Algorithm/solvelpform.jl
  src/Algorithm/storage.jl
  src/Algorithm/treesearch.jl
  src/Algorithm/utilities/optimizationstate.jl
  src/Algorithm/utilities/record.jl
  src/ColunaBase/ColunaBase.jl
  src/ColunaBase/interface.jl
  src/MathProg/MathProg.jl
  src/MathProg/formulation.jl
  src/MathProg/incumbents.jl
  src/MathProg/optimizationresults.jl
  src/MathProg/optimizerwrappers.jl
  src/MathProg/reformulation.jl
  src/MathProg/types.jl
  src/optimize.jl
  test/full_instances_tests.jl
Labels: documentation, enhancement

#337 Fix activate!
  src/MathProg/new_varconstr.jl
Labels: bug

#331 clean setvarconstr!
  docs/make.jl
  docs/src/dev/formulation.md
  src/Algorithm/benders.jl
  src/Algorithm/branching/varbranching.jl
  src/Algorithm/colgen.jl
  src/Algorithm/formstorages.jl
  src/Algorithm/preprocessing.jl
  src/MOIcallbacks.jl
  src/MathProg/MOIinterface.jl
  src/MathProg/MathProg.jl
  src/MathProg/clone.jl
  src/MathProg/constraint.jl
  src/MathProg/decomposition.jl
  src/MathProg/formulation.jl
  src/MathProg/manager.jl
  src/MathProg/new_varconstr.jl
  src/MathProg/optimizerwrappers.jl
  src/MathProg/reformulation.jl
  src/MathProg/solutions.jl
  src/MathProg/varconstr.jl
  src/MathProg/variable.jl
  test/unit/MathProg/variables.jl
  test/unit/constraint.jl
  test/unit/variable.jl
Labels: MathProg
