Repository atoptima/Coluna.jl, pull requests merged in 2021-04, with the labels that each got.

#485 Missing unit tests in Bounds and Solutions
  .github/workflows/ci.yml
  Project.toml
  src/ColunaBase/solsandbounds.jl
  test/unit/containers/solsandbounds.jl
Labels: design, tests

#475 Remove code for spMv operation in colgen
  .github/workflows/ci.yml
  Project.toml
  src/Algorithm/Algorithm.jl
  src/Algorithm/colgen.jl
Labels: performance

#502 Fix conditions to restart colgen when using lazy cut gen
  src/Algorithm/colgen.jl
Labels: bug

#503 StorageContainer -> Storage & fix arg order for restore_from_records
  src/Algorithm/branching/varbranching.jl
  src/Algorithm/conquer.jl
  src/Algorithm/interface.jl
  src/Algorithm/storage.jl
Labels: design

#507 Move storage & records in ColunaBase
  src/Algorithm/Algorithm.jl
  src/Algorithm/colgenstabilization.jl
  src/Algorithm/conquer.jl
  src/Algorithm/data.jl
  src/Algorithm/formstorages.jl
  src/Algorithm/preprocessing.jl
  src/ColunaBase/ColunaBase.jl
  src/ColunaBase/storage.jl
  src/optimize.jl
Labels: design

#510 Deletion of `AbstractData`
  docs/src/dev/todo.md
  src/Algorithm/Algorithm.jl
  src/Algorithm/basic/cutcallback.jl
  src/Algorithm/basic/solveipform.jl
  src/Algorithm/basic/solvelpform.jl
  src/Algorithm/benders.jl
  src/Algorithm/branching/branchingalgo.jl
  src/Algorithm/branching/branchinggroup.jl
  src/Algorithm/branching/branchingrule.jl
  src/Algorithm/branching/varbranching.jl
  src/Algorithm/colgen.jl
  src/Algorithm/conquer.jl
  src/Algorithm/data.jl
  src/Algorithm/divide.jl
  src/Algorithm/interface.jl
  src/Algorithm/preprocessing.jl
  src/Algorithm/treesearch.jl
  src/ColunaBase/ColunaBase.jl
  src/ColunaBase/storage.jl
  src/MathProg/formulation.jl
  src/MathProg/reformulation.jl
  src/optimize.jl
  test/user_algorithms_tests.jl
Labels: design
